### ISSUE TITLE
ASSUME_ALWAYS_YES=1 generates an error

### ISSUE THREAD

**Issue by nulldowntime** [xaque208/puppet-pkgng#54] opened 2014-08-21 13:21 UTC
ASSUME_ALWAYS_YES=1 in is no longer valid (in lib/facter/pkgng.rb). I'm running pkg-1.3.5.1 on FreeBSD 10.0), it generates an error:

pkg: Invalid type for environment variable ASSUME_ALWAYS_YES, got 1, while expecting a boolean

So that needs to be ASSUME_ALWAYS_YES=true, probably conditional on the pkg version. I'm not exactly sure as of which version of pkg this became an error.

**Comment by xaque208** [comment] 2015-03-11 03:13
This no longer seems to be an issue in 1.4.12.  Can you confirm?

**Comment by bartekrutkowski** [comment] 2015-03-13 10:04
I can confirm, that on 10.1-RELEASE-p6 with pkg-1.4.12, the ASSUME_ALWAYS_YES=1 is no longer resulting in an error (but still, doesnt work and pkg asks for 'y/N' confirmations) and ASSUME_ALWAYS_YES=yes works as expected (pkg doesnt ask for 'y/N' confirmations.

**Comment by xaque208** [comment] 2016-04-21 04:20
The string ASSUME_ALWAYS_YES no longer exists in this repo.  Closing issue.

**Closed by xaque208** 2016-04-21 04:20 UTC
